### ISSUE TITLE
failing installation on GitHub Actions

### ISSUE THREAD

**Issue by chrisguttandin** [jazz-soft/midi-test#3]
I noticed that installing `midi-test` fails on GitHub Actions as of late. I'm using `actions/setup-node@v3` to install and run Node.js at version 18. The configuration should be the same as the one used for testing this package. The change that's causing this problem must have been introduced in the last two weeks.

The full logs are available here: https://github.com/chrisguttandin/subscribable-things/actions/runs/6778261074/job/18423906611. But I believe they can't be viewed publicly. Here is a copy/pasted version:

```txt
npm ERR! code 1
npm ERR! path /Users/runner/work/subscribable-things/subscribable-things/node_modules/midi-test
npm ERR! command failed
npm ERR! command sh -c node-gyp rebuild
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.4.0
npm ERR! gyp info using node@18.18.2 | darwin | x[6](https://github.com/chrisguttandin/subscribable-things/actions/runs/6778261074/job/18423906611#step:5:7)4
npm ERR! gyp info find Python using Python version 3.12.0 found at "/usr/local/bin/python3"
npm ERR! gyp http GET https://nodejs.org/download/release/v18.18.2/node-v18.18.2-headers.tar.gz
npm ERR! gyp http 200 https://nodejs.org/download/release/v18.18.2/node-v18.18.2-headers.tar.gz
npm ERR! gyp http GET https://nodejs.org/download/release/v18.18.2/SHASUMS256.txt
npm ERR! gyp http 200 https://nodejs.org/download/release/v18.18.2/SHASUMS256.txt
npm ERR! gyp info spawn /usr/local/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/Users/runner/hostedtoolcache/node/18.18.2/x64/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/runner/work/subscribable-things/subscribable-things/node_modules/midi-test/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/runner/hostedtoolcache/node/18.18.2/x64/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/runner/Library/Caches/node-gyp/18.18.2/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/Users/runner/Library/Caches/node-gyp/18.18.2',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/Users/runner/hostedtoolcache/node/18.18.2/x64/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/Users/runner/Library/Caches/node-gyp/18.18.2/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/Users/runner/work/subscribable-things/subscribable-things/node_modules/midi-test',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! Traceback (most recent call last):
npm ERR!   File "/Users/runner/hostedtoolcache/node/18.18.2/x64/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py", line 42, in <module>
npm ERR!     import gyp  # noqa: E402
npm ERR!     ^^^^^^^^^^
npm ERR!   File "/Users/runner/hostedtoolcache/node/18.18.2/x64/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 9, in <module>
npm ERR!     import gyp.input
npm ERR!   File "/Users/runner/hostedtoolcache/node/18.18.2/x64/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 19, in <module>
npm ERR!     from distutils.version import StrictVersion
npm ERR! ModuleNotFoundError: No module named 'distutils'
npm ERR! gyp ERR! configure error 
npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onCpExit (/Users/runner/hostedtoolcache/node/18.18.2/x64/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:325:16)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:51[7](https://github.com/chrisguttandin/subscribable-things/actions/runs/6778261074/job/18423906611#step:5:8):2[8](https://github.com/chrisguttandin/subscribable-things/actions/runs/6778261074/job/18423906611#step:5:9))
npm ERR! gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:2[9](https://github.com/chrisguttandin/subscribable-things/actions/runs/6778261074/job/18423906611#step:5:10)2:[12](https://github.com/chrisguttandin/subscribable-things/actions/runs/6778261074/job/18423906611#step:5:13))
npm ERR! gyp ERR! System Darwin 21.6.0
npm ERR! gyp ERR! command "/Users/runner/hostedtoolcache/node/[18](https://github.com/chrisguttandin/subscribable-things/actions/runs/6778261074/job/18423906611#step:5:19).18.2/x64/bin/node" "/Users/runner/hostedtoolcache/node/18.18.2/x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd /Users/runner/work/subscribable-things/subscribable-things/node_modules/midi-test
npm ERR! gyp ERR! node -v v18.18.2
npm ERR! gyp ERR! node-gyp -v v9.4.0
npm ERR! gyp ERR! not ok
```

I also tried to use `ubuntu-latest` instead of `macos-latest` by making these changes: https://github.com/chrisguttandin/subscribable-things/commit/32b65a4da1ef49ffaad76d1a294ddc3be3284c72.

The installation worked but the tests failed at runtime with the following error message:

```txt
Platform dependent initialization failed.
```

**Comment by jazz-soft** [comment]
Thanks for letting me know! I'll try to investigate...

**Comment by chrisguttandin** [comment]
Thanks a lot @jazz-soft. Please let me know if there is anything I can help with, test, or double check.

**Comment by jazz-soft** [comment]
The problem seems to be with the node-gyp that does not work with Python 3.12 that is the default version on Mac now.
Not sure how to fix it except of waiting till they fix the node-gyp.
Please see https://github.com/nodejs/node-gyp/issues/2869

**Comment by chrisguttandin** [comment]
Many thanks for finding the root cause. I [applied the workaround](https://github.com/chrisguttandin/subscribable-things/commit/0885349c4176eae2d5c7405ad712579eecb214a0) mentioned in the issue linked above. It works as expected. The build error is gone.

**Comment by jazz-soft** [comment]
Wow! Thanks a lot! That worked for me too!
